name: GenerateJson

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Give executable permission
        run: chmod +x generateList.swift
        
      - name: Run script and write file
        run: swift generateList.swift
